"""unique constraint on investor name

Revision ID: 993669543697
Revises: eb767c4faede
Create Date: 2024-07-31 09:36:35.652949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993669543697'
down_revision = 'eb767c4faede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investors', schema=None) as batch_op:
        batch_op.create_unique_constraint("uk_investor_name", ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investors', schema=None) as batch_op:
        batch_op.drop_constraint("uk_investor_name", type_='unique')

    # ### end Alembic commands ###
