"""Fist migration

Revision ID: eb767c4faede
Revises: 
Create Date: 2024-07-31 06:34:39.562454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb767c4faede'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investory_type', sa.Enum('ASSET_MANAGER', 'BANK', 'FUND_MANAGER', 'WEALTH_MANAGER', name='investorytypeenum'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commitments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.Column('asset_class', sa.Enum('HEDGE_FUNDS', 'INFRASTRUCTURE', 'NATURAL_RESOURCES', 'PRIVATE_DEBT', 'PRIVATE_EQUITY', 'REAL_ESTATE', name='assetclassenum'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commitments')
    op.drop_table('investors')
    # ### end Alembic commands ###
